name: Running Test

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
  push:
    branches:
      - 'test-workflow'  # This triggers the workflow when pushing to this branch (optional)
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 22
          cache: 'gradle'

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -d > app/google-services.json  # Ensure google-services.json is set correctly in secrets

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test  # Adjust to your project's test task (e.g., testDebug, testRelease, etc.)
